# Generated by Django 4.0.2 on 2022-02-07 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_worker_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worker',
            options={'ordering': ['-name']},
        ),
    ]
