# Generated by Django 4.0.2 on 2022-02-07 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_worker_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worker',
            options={'ordering': ['surname']},
        ),
    ]
